### ISSUE TITLE
Replace tiny-sha256 with bitcoin_hashes and cbor with serde_cbor?

### ISSUE THREAD

**Issue by icota** [dspicher/ur-rs#35]
I am working on a project that is targeting `wasm32-unknown-unknown` and am having issues due to these two dependencies. `cbor` ultimately depends on `rustc-serialize` which makes it impossible to build for this target and `tiny-sha256` breaks at runtime with `attempt to shift right with overflow`.

I have done some quick testing and replacing the two with `bitcoin_hashes` and `serde_cbor` fixes these issues for me.

Would you be open to PRs in this sense? `cbor` is unmaintained and `tiny-sha256` seems stale as well.

**Comment by FoundationKen** [comment]
Specifically these repos:

  - `bitcoin_hashes`: https://github.com/rust-bitcoin/bitcoin_hashes

  - `serde_cbor`: https://github.com/pyfisch/cbor

As a side note, we also ported UR to Python/MicroPython previously and would be happy to help maintain this Rust repo too if that is of interest.

  - https://github.com/Foundation-Devices/foundation-ur-py

**Comment by dspicher** [comment]
Hey!
Yes, I'm definitely open to merging such PRs! Glad to see that people are using this :)

**Comment by icota** [comment]
We're happy to hear that. PRs incoming :)
